name: ${project.name}
main: ${project.groupId}.${project.name}
version: ${project.version}
authors: [E_NeLsOn]
depend: [PlaceholderAPI,NBTAPI]
softdepend: [WorldGuard]
api-version: 1.21
commands:
  acustomblocks:
    usage: /acustomblocks <about|reload|give>
permissions:
  acustomblocks.admin:
    default: op
