name: ${project.name}
main: ${project.groupId}.${project.name}
version: ${project.version}
authors: [E_NeLsOn]
depend: [SopLib, PlaceholderAPI, NBTAPI]
api-version: 1.16
commands:
  acustomblocks:
    usage: /acustomblocks
permissions:
  acustomblocks.admin:
    default: op
